[package]
name = "jenkins-build-stats"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]

[dependencies]
envy="0.3"
hyper="0.10"
serde="1.0"
serde_derive="1.0"
serde_json="1.0"
hyper-native-tls = "0.2"
url="1.4"